### ISSUE TITLE
why does ldd /opt/cryptsetup/sbin/cryptsetup say it's not dynamic?

### ISSUE THREAD

**Issue by soul9** [sabotage-linux/sabotage#313]
# ldd /opt/cryptsetup/sbin/cryptsetup 
    ldd: /opt/cryptsetup/sbin/cryptsetup: Not a valid dynamic program

cryptsetup is dynamic and needs quite a few .so-s

**Comment by rofl0r** [comment]
can't reproduce:
```
root:/$ ldd
musl libc
Version 1.1.8
Dynamic Program Loader
Usage: ldd [options] [--] pathname
root:/$ ldd /opt/cryptsetup/sbin/cryptsetup 
	/lib/ld-musl-x86_64.so.1 (0x7f82ec7ba000)
	libcryptsetup.so.4 => /lib/libcryptsetup.so.4 (0x7f82ec59f000)
	libpopt.so.0 => /lib/libpopt.so.0 (0x7f82ec396000)
	libc.so => /lib/ld-musl-x86_64.so.1 (0x7f82ec7ba000)
	libdevmapper.so.1.02 => /lib/libdevmapper.so.1.02 (0x7f82ec160000)
	libssl.so.32 => /lib/libssl.so.32 (0x7f82ebf03000)
	libcrypto.so.32 => /lib/libcrypto.so.32 (0x7f82ebb2d000)
root:/$ 
```

**Comment by soul9** [comment]
how can this be?
root:/$ ldd
musl libc
Version 1.1.8
Dynamic Program Loader
Usage: ldd [options] [--] pathname
root:/$ ldd /opt/cryptsetup/sbin/cryptsetup
ldd: /opt/cryptsetup/sbin/cryptsetup: Not a valid dynamic program
root:/$

**Comment by rofl0r** [comment]
tried latest version of cryptsetup as well
```
root:/$ ldd
musl libc
Version 1.1.8
Dynamic Program Loader
Usage: ldd [options] [--] pathname
root:/$ ldd /opt/cryptsetup/sbin/cryptsetup 
	/lib/ld-musl-x86_64.so.1 (0x7f7fae712000)
	libcryptsetup.so.4 => /lib/libcryptsetup.so.4 (0x7f7fae4f3000)
	libpopt.so.0 => /lib/libpopt.so.0 (0x7f7fae2ea000)
	libc.so => /lib/ld-musl-x86_64.so.1 (0x7f7fae712000)
	libdevmapper.so.1.02 => /lib/libdevmapper.so.1.02 (0x7f7fae0b4000)
	libssl.so.32 => /lib/libssl.so.32 (0x7f7fade57000)
	libcrypto.so.32 => /lib/libcrypto.so.32 (0x7f7fada81000)
root:/$ /opt/cryptsetup/sbin/cryptsetup --version
cryptsetup 1.6.7
```

**Comment by rofl0r** [comment]
(on x86_64, for the record)

**Comment by soul9** [comment]
So how can this be? What software do you install on your machine? world? I only install stage1 and then manually install some software (like cryptsetup). do you think this might be because of some sort of symlink confusion? what kernel version do you have? maybe this is in relation to btrfs or squashfs?

**Comment by bitshark** [comment]
There's a few reasons for this.... One that sticks out is this:  Depending on the cflags and ldflags,  it's possible that (1) only dynamic libs (.so are built).. (2) only static libs are built (.a) , and (3) both can be built, especially with two builds in a row with different flags.

The dynamic linker will first use .so it finds, then use .a.   Most likely you have staticly linked cryptlib which depends on something external that was built with shared linking.  Hope this helps.

**Comment by soul9** [comment]
no. I do not. this binary depends on having /lib/libcrypt.so, it *will not work* without it. ldd thinks it is a static executable though.
I ran into this when making an initramfs for encrypted filesystems: if I do not copy many shared libs, the executable will fail mysteriously.

**Comment by bitshark** [comment]
Ah okay.  I don't know your issue in particular -- but  I'm familiar these problems _in general_  because I recently made a 'static compiled linux' using Sabotage.

So for your problem -- initramfs is the perfect example for why you need static compiled binaries .   But even with the static binaries, there can be failures I think.    One example is the process ordering.... . .But does a statically linked cryptsetup call any external programs?

And is it even an ELF binary?   I'm not so sure...    On my /bin/cryptsetup it's an ELF binary with shared libs...

/src/pkg # ldd /bin/cryptsetup 
	/lib/ld-musl-x86_64.so.1 (0x55a4ed156000)
	libcryptsetup.so.4 => /lib/libcryptsetup.so.4 (0x7f12d87d5000)
	libpopt.so.0 => /lib/libpopt.so.0 (0x7f12d85cc000)
	libc.so => /lib/ld-musl-x86_64.so.1 (0x55a4ed156000)
	libdevmapper.so.1.02 => /lib/libdevmapper.so.1.02 (0x7f12d8396000)
	libssl.so.32 => /lib/libssl.so.32 (0x7f12d813f000)
	libcrypto.so.32 => /lib/libcrypto.so.32 (0x7f12d7d99000)

BUT... is it so in the build directory?

/src/build/cryptsetup/cryptsetup-1.6.7 # ./src/cryptsetup --version
cryptsetup 1.6.7
/src/build/cryptsetup/cryptsetup-1.6.7 # ldd ./src/cryptsetup
ldd: ./src/cryptsetup: Not a valid dynamic program

hmm...   looks like your problem....

### But It's a shell script wrapper, heh.  So static / dynamic not applicable directly to it.   
### The real ELF binary is in src/.libs/cryptsetup

Anyway...  that could be part of the discrepancy perhaps.

Do you want to make a staticly linked cryptsetup for initramfs?  It's possible... The starting point I think would be rebuild cryptsetup....

My static build failed because I don't have static devmapper library built...

/src/build/cryptsetup/cryptsetup-1.6.7 # ./configure --enable-static --enable-static-cryptsetup --with-crypto_backend=openssl

# make
...
/bin/ld: cannot find -ldevmapper
collect2: error: ld returned 1 exit status
make[2]: *** [cryptsetup.static] Error 1
make[2]: Leaving directory `/src/build/cryptsetup/cryptsetup-1.6.7/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/src/build/cryptsetup/cryptsetup-1.6.7'
make: *** [all] Error 2

/src/build/cryptsetup/cryptsetup-1.6.7 # ls /lib/libdevm*
/lib/libdevmapper.so       /lib/libdevmapper.so.1.02

**Comment by soul9** [comment]
strange. it is not a script. but now ldd works fine. weird!
