### ISSUE TITLE
Why build GCC3 to build GCC4?

### ISSUE THREAD

**Issue by robotanarchy** [sabotage-linux/sabotage#363]
So stage0 builds GCC3 (except for ARM), and then stage1 builds GCC4. *(A friend joked, that stage2 then builds GCC5 :smile:  )*

What is the reason for that?

My guess: GCC3 builds faster, and we need to build GCC a second time anyway (to use musl instead of glibc/whatever the host system has). Is that the case?

**Comment by rofl0r** [comment]
we need a gcc in the rootfs, and since we dont want to copy glibc stuff inside there, we build a static linked gcc3 because 1) it's fast to compile 2) sufficient for all packages used in stage0/upto and including gcc474 2) doesn' t have external dependencies that complicate the build.
another reason is that it gives us reproducible builds since everything past gcc3 is always built with the same toolchain/options. so if 2 ppl build for the same arch but different host system from the same git commit, all binaries except the throw-away gcc3 are identical.

**Comment by rofl0r** [comment]
correction: the binaries *should* be identical, however there seem to be issues due to inserted timestamps as noted here https://reproducible.debian.net/index_issues.html
something that needs our attention in the near future...

**Comment by robotanarchy** [comment]
Thanks for clarifying!

And good to know that you're somewhat trying to support reproducible builds, I've been following that too.

With *that needs our attention in the near future...*, you mean the Linux/OSS community as a whole, right? Because for the source based distribution that sabotage is, it doesn't really matter if the built packages are bit-perfect since the binaries shouldn't be shared much anyway. Or will it become a binary distribution at some point in time?

**Comment by rofl0r** [comment]
a long term goal i have in mind is to provide precompiled packages as well, since some packages require insane amounts of RAM or time to be built. for example, it's next to impossible to compile firefox on an ARM netbook. so if you dont have high-end hw, it may be preferable to fetch a precompiled binary, as long as you can trust it (i.e. other developers can reproduce the exact same result and confirm that it's untainted).
so the interest is more distribution-specific.

**Comment by robotanarchy** [comment]
nice!
