### ISSUE TITLE
Patches for missing queue.h, new pkg f2fs-tools

### ISSUE THREAD

**Issue by bkauler** [sabotage-linux/sabotage#405]
I tried to submit these at the mail-list, for perusal by a sabotage developer, but the email attachments didn't work. So, I will stick them in here.

Please read my mail-list post:
http://openwall.com/lists/sabotage/2016/04/29/3

And a whole bunch of my posts:
http://openwall.com/lists/sabotage/

The mail-list seems dead. Are any developers monitoring it?

Patches attached. I'm a beginner with Sabotage, so kindly give any advice on possible improvements.

Regards,
Barry Kauler

[sabotage-fix-missing-sys-queue.h-header.patch.txt](https://github.com/sabotage-linux/sabotage/files/242503/sabotage-fix-missing-sys-queue.h-header.patch.txt)
[sabotage-new-pkg-f2fs-tools.patch.txt](https://github.com/sabotage-linux/sabotage/files/242505/sabotage-new-pkg-f2fs-tools.patch.txt)

**Comment by rofl0r** [comment]
hi, thanks for showing up here and your reports on the list.
indeed the mailing list is almost dead, and i keep forgetting to look into there.
the mailing list is a relic from the first sabotage incarnation (written by @chneukirchen , later forked by @pikhq and finally by me). i'd probably never have created it, since github features all facilities offered by mailing lists in an imo nicer packet.
you can open and discuss issues, pull request and comment with on a single-line granularity directly in the diffs.
now as to the things you reported on the mailing list:
1) build failures on your ubuntu 16 based host:
    it would be nice to get them fixed. however that would require looking into your build logs; i noticed that butch and patch failed to build. do you still have the buildlogs around ?
2) tmux sha512 mismatch : fixed in https://github.com/sabotage-linux/sabotage/commit/9bb14b35d211b9b930dfed98de69615705520e9c
3) xmms2 build error: fixed in https://github.com/sabotage-linux/sabotage/commit/c5631fabe9f284bf5cd0e94257665d66ddb0c01b
4) usage of LDFLAGS etc: please use KEEP/pkg_skel/autoconf as a template to make new packages. it has everything arranged in an optimal way, and usually just works.
5) sys/queue.h: i know that it would be easier to "just provide it".
  however that is not in the spirit of musl, rather than going the path of least resistance we want to get things fixed. since sys/queue.h is a non-standard, standalone header, projects using it should not assume its existence but rather provide it in their source tree.

as for your package addition: i'll gladly merge it once you fixed it in a way that doesn't necessite providing the copyrighted header in sabotage itself; but please do so in form of a pull request which makes review much easier. thanks!

**Comment by bkauler** [comment]
Thanks for the response.

Would you require that I test cross-compile before submitting a new package?
I am currently only doing a native build.

**Comment by rofl0r** [comment]
no, i don't require that. if you can just leave the cross-compile related boilerplate i will test it later.

re your question about libuuid: we have a pkg libuuid, so you should just add that to deps
(i hope i didnt forget other questions).
