### ISSUE TITLE
Build of gperf fails

### ISSUE THREAD

**Issue by aario** [sabotage-linux/sabotage#560]
The error message is:
`bad value (generic) for -mtune= switch`
Searching Internet it seems like I should define MARCH. I don't know what to set as the value of MARCH. I don't know how to define the MARCH or $optcflags variable.

PS: A was set to x86_64 in /src/config. Setting that to native fixes the problem.

**Comment by rofl0r** [comment]
what were the contents of your etc/butch-optflags.sh ?
by default, -march=native is used. that works everywhere.
you should never ever set A in your config to something undocumented like "native" or all hell will break loose. the only tested values are those that are commented out in the template.
i just did a fresh build from 0 to xorg, and the only issue i encountered was the xkeyboard-config thing. both mesalib and gperf compile flawlessly with default `butch-optflags.sh`

**Comment by rofl0r** [comment]
i apologize for remembering wrong, we do set -mtune=generic in KEEP/etc/butch-optflags.sh ... however only on compiler that can deal with it. so since it works for everyone else, there must be some other problem specific to your configuration. please paste the contents of your butch-optflags.sh and the output of gcc -v. i suspect there's some issue with your toolchain.

**Comment by rofl0r** [comment]
could you please reply ? if not i'll assume the issue was PEBKAC and will close this tomorrow.

**Comment by rofl0r** [comment]
EWORKSFORME
