### ISSUE TITLE
Multi architecture installations possible?

### ISSUE THREAD

**Issue by cesss** [sabotage-linux/sabotage#653]
Hi!

Reading the Cookbook, I couldn’t find if you can install packages in several architectures in the same Sabotage system: For me it would be very convenient to build packages for i386, x86_64, PPC, and MIPS and install them on a different tree for each arch. Of course the host would only be able to execute native code, but in this way it would be very easy to just copy installed packages to other hosts than can execute them.

Besides, Intel hosts would be able to run packages both on the i386 and x86_64 trees.

Is this possible?

Thanks!

**Comment by rofl0r** [comment]
yeah i do that. for example, i have a directory `~/x-prefix` which contains sub dir for e.g. mips, arm, powerpc, each one containing a rootfs directory structure and a `config` file for the cross-compiler setup (see section in README about cross-compiling).

i386 binaries work fine with the default saboage x86_64 kernel config, too.

**Comment by cesss** [comment]
Thanks!! Then I think I’m going to have a lot of fun with Sabotage!! BTW, how does the musl dynamic loader know what’s the prefix for the dynamic libraries of a 64bit or 32bit Intel executable?

**Comment by rofl0r** [comment]
musl uses a file /etc/ld-musl-$ARCH.conf which can contain a list of paths for library search on that arch. http://www.musl-libc.org/doc/1.0.0/manual.html

**Comment by cesss** [comment]
I've been reading through the source and this distribution is really great. I think it's the one that most closely matches the kind of system I want to have for the upcoming years. Thanks a lot for developing it!! The only thing I miss is using LLVM instead of GCC, but I'll try to build it with LLVM during the next months, and I'll tell you if I managed to get a Sabotage build based on LLVM-musl

**Comment by rofl0r** [comment]
> most closely matches the kind of system I want to have for the upcoming years

glad to hear!

> The only thing I miss is using LLVM instead of GCC

why would that be ? clang/llvm is worse than GCC on about any possible metric.
the corporations behind it do have a better marketing budget though. building LLVM/Clang takes *a lot* more time and resources. I've recently seen distros switch their build recipes to build clang with -Os, otherwise they wouldn't have been able to link it together because the object files were so big they wouldn't fit into 24-bit relocations as used by some archs. also, Clang is full of hacks that break when used with musl, needing a big number of patches to make it even compile. due to these reasons, and the fact that LLVM constantly changes its API, i consider any languages using it as a backend a fad in history and a waste of time, since if they don't constantly update their interface code, their product will stop working after the very next LLVM release. the situation this creates is that different packages require different LLVM versions, which causes tons of installed bloat and situations like when you want to bootstrap rust from source, you have to build and patch (and waste a lot of time doing so) every single LLVM version that's used along the way.
