### ISSUE TITLE
add linux kernel 5.9.x

### ISSUE THREAD

**Issue by ucodelukas** [sabotage-linux/sabotage#680]
i would like to know how i properly contribute the build files for the new kernel

**Comment by rofl0r** [comment]
is 5.9 scheduled to be a long-time support kernel ?
either way checkout #675 for how addition of kernel 5.4 was done, another kernel would follow the same basic principles.

**Comment by ucodelukas** [comment]
Oh you only want LTS kernels?
Understandable

Nevermind then

**Comment by rofl0r** [comment]
good we didn't add it - 5.9 has surprisingly been marked as EOL.
surprisingly because according to past developments, it should have been the next LTS candidate (every 5th major release has been tagged LTS since at least 4.4: 4.4 -> 4.9 -> 4.14 -> 4.19 -> 5.4). so my suspicion is that 5.10 will be next then, and maybe it would make sense to see what it takes to get it to work with the existing patch/feature set.
