### ISSUE TITLE
TCC compiler/asm/linker

### ISSUE THREAD

**Issue by afsec** [sabotage-linux/sabotage#681]
Sabotage Linux is a great idea. Maybe would be interesting if sabotage build on top of TinyCC + MUSL.
I tried some of these commands without success on make tcc statically linked which will open a door of other statically linked binaries.

## Make buildroot

```
mkdir -p /root/tmp
cd tmp
wget https://musl.libc.org/releases/musl-1.2.1.tar.gz
wget https://download.savannah.gnu.org/releases/tinycc/tcc-0.9.27.tar.bz2
tar -xvf musl-1.2.1.tar.gz
tar -xvf tcc-0.9.27.tar.bz2
```

## Build MUSL (1.2.1)
```
cd /root/tmp/musl-1.2.1/
./configure --disable-shared
make
```

## Build First Round (./dist)

```
cd /root/tmp/tcc-0.9.27/
./configure --config-musl --extra-cflags="-static -L$HOME/tmp/musl-1.2.1/lib -lc" --prefix=$(pwd)/dist && make -j4 && make install
```

## Build Second Round (./dist2)
```
make clean ; ./configure --config-musl --enable-static --libpaths="$HOME/tmp/musl-1.2.1/lib" --cc=$PWD/dist/bin/tcc --extracflags="-static -nostdinc" --prefix=$(pwd)/dist2 && make && make install
```

Does anyone agree/disagree about it? Is it pointless or useful for make a linux distro? 

Regards

**Comment by rofl0r** [comment]
tcc is fascinating because it is so fast, so i did numerous experiments with it.
however i found that it's not really useful for anything.
it doesn't support lots of C99 features that it e.g. use in my own projects, it's debug info is next to unusable, optimization is non-existent so the code it generates is dog-slow, it doesn't support inline asm, the way it provides varargs (stdarg.h) is incompatible with musl, and generally can't compile musl. if you're lucky it would work with maybe 10% of the projects in sabotage's pkg/, and since tcc is maintained by a mob (i.e. mob branch, where anyone can push to) it's prone to be really buggy. imo a much better choice is cproc, which is also fast (though not nearly as fast), or gcc 3.4.6 which is like 5-10x faster than GCC 6. with gcc 3.4.6 you basically get a superb codegen, full C99 support, GNU extensions, proper debug info, inline asm etc. however the linux kernel needs GCC 4+ since like 10 years so you'd need a separate full-blown compiler anyways.

**Comment by afsec** [comment]
@rofl0r I agree 100%. I had that musl stdarg.h issue. Thanks for sharing your great experience. Regards.
