### ISSUE TITLE
Any plans for a new release/build ISO file?

### ISSUE THREAD

**Issue by terremoth** [sabotage-linux/sabotage#711]

**Comment by rofl0r** [comment]
to be frank, no. there's a quite recent rootfs on the barfooze ftp and not much (or nothing) changed to the core system since its release. it will give you everything to get started building more packages, and after all, the entire distro is meant to be built from source anyway. so maybe it's best if you just give it a try. it takes only 3 min to build the stage0 using a modern desktop computer.
